services:
  - name: silu
    type: web
    env: node
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    rootDir: .
    region: singapore
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
